### ISSUE TITLE
How to use framework types

### ISSUE THREAD

**Issue by imgen** [config-r/config-r#191]
I want to use `ConnectionStringSettings` type from `System.Configuration.dll`, but when I try to use it in Config.csx file, it throws exception. Then I tried to use the Assembly.Load approach presented in below wiki page
https://github.com/config-r/config-r/wiki/Adding-script-references-to-dynamically-loaded-assemblies
like this

// MyApp.exe
var assembly = Assembly.Load("System.Configuration.dll");
Config.GlobalAutoLoadingReferences.Add(assembly);
var myConfigItem = Config.Global.Get<object>("foo");

// MyApp.csx
Add("myconfigitem", new SomeTypeFromMyAssembly());

but I got an DllNotFound exception on first line. What should I do?

**Comment by adamralph** [comment]
@imgen thanks for raising this. Which line of code throws the exception? Is it `var assembly = Assembly.Load("System.Configuration.dll");`?

If so, perhaps try referencing the assembly and doing this instead?

`Config.GlobalAutoLoadingReferences.Add(typeof(ConnectionStringSettings).Assembly);`

**Comment by imgen** [comment]
Yes, you are right, it threw exception in the `Assembly.Load` line. Thanks for the tip. I obviously overlooked this. Maybe you can add this to the wiki article.

**Comment by adamralph** [comment]
@imgen I've edited the wiki page https://github.com/config-r/config-r/wiki/Adding-script-references-to-dynamically-loaded-assemblies

What do you think?

**Comment by imgen** [comment]
@adamralph Great! You rock!

**Comment by adamralph** [comment]
Ah, of course, thanks!

**Comment by imgen** [comment]
@adamralph you are welcome

**Comment by adamralph** [comment]
@imgen I guess your question has been answered then? Please feel free to re-open if you need more info. Thanks again for raising the issue.
