### ISSUE TITLE
Remove obsolete members

### ISSUE THREAD

**Issue by adamralph** [config-r/config-r#192]
Everything that was obsoleted in 0.9.0

**Comment by adamralph** [comment]
@teabaggs the only remaining obsolete is https://github.com/config-r/config-r/blob/874f2c538cbd1dfe59e4921db333f43b9b32f405/src/ConfigR/Configurator.cs

Would you like to have the honour of removing that too? :wink:

**Comment by teabaggs** [comment]
Yeah, no problem. I'll check it tonight. I excluded from project in VS and
forgot to delete the actual file I guess.

**Comment by adamralph** [comment]
https://www.nuget.org/packages/ConfigR/0.13.0
https://github.com/config-r/config-r/releases/tag/0.13.0

**Comment by adamralph** [comment]
@teabaggs I couldn't find your twitter handle but I have you a shout out in https://twitter.com/adamralph/status/656197835357036544

Thanks again!
