### ISSUE TITLE
Log message is incorrect when script fails to execute

### ISSUE THREAD

**Issue by adamralph** [config-r/config-r#194]
> Error: Failed to execute System.Runtime.ExceptionServices.ExceptionDispatchInfo

**Comment by adamralph** [comment]
The log message is in fact redundant since the exception is thrown up the stack anyway. Just remove.

**Comment by cmatskas** [comment]
Hey @adamralph , is this still an issue?

**Comment by adamralph** [comment]
@cmatskas it's been merged to dev, just hasn't been released yet. As soon as https://github.com/config-r/config-r/issues/192 is complete I'll probably push out 0.13.0 which will contain this bug fix.

**Comment by cmatskas** [comment]
Pity...was hoping to give this a go :) Maybe if you put a label (upforgrabs) or similar against items need fixing then me and other contributors will know what to pick next?

**Comment by adamralph** [comment]
Good idea. I've done it for several other projects but never got round to doing it for ConfigR. I've added the label for both this repo and the samples repo.

**Comment by adamralph** [comment]
Will hopefully be added to http://up-for-grabs.net/ soon - https://github.com/dahlbyk/up-for-grabs.net/pull/243

**Comment by cmatskas** [comment]
Excellent stuff buddy. I'll what's * "up for grabs"!* See what I did there? Lol

**Comment by adamralph** [comment]
https://www.nuget.org/packages/ConfigR/0.13.0
https://github.com/config-r/config-r/releases/tag/0.13.0
