### ISSUE TITLE
How do I reference an assembly from a website config?

### ISSUE THREAD

**Issue by cmatskas** [config-r/config-r#199]
If I try to reference an external dll in my ConfigR file on a WebApi project, when I attempt to access the values in the configr file (i.e. Web.csx) I get a **"FileNotFoundException"** with Additional information: **Assembly not found**

The Web.csx file is set to Copy Always and I can verify that the referenced dll exists in the the same bin directory as the Web.csx file. The way I reference the external dll is:

    #r "Custom.Library.dll"
    using Custom.Library.Model;
        //... omitted for clarity

If I remove the external reference, the code works as expected.

**Comment by cmatskas** [comment]
After chatting with @adamralph for a bit, it turns out that the way to resolve this is to change the reference path to the target dll as per the example below:

#r "bin\Custom.Library.dll"

Doing so allows the configR file to load the necessary dlls and should work as expected. I will do a pull request to update the docs and maybe provide an example

**Comment by adamralph** [comment]
For reference: for a web app, the Web.csx file should not be set to copy to the output folder. Rather, it should live in the root, alongside Web.config. It is this file that is executed at runtime. If Web.csx is set to copy to the output folder then it also appears there, but is not used. If someone sees this and assumes it is being executed then the path used in `#r` doesn't make any sense, but if it is recognised that the Web.csx in root is being executed then the path does make sense.

I agree that this should be put in to the docs somewhere, and it's probably good if the web app example is enhanced to include a `#r` in the web.csx.

**Comment by adamralph** [comment]
Closing, since the question is answered and we've recognised the need for a docs enhancement - raised as #203
