### ISSUE TITLE
Add documentation for how to use Web.csx

### ISSUE THREAD

**Issue by adamralph** [config-r/config-r#203]
*Spun off from https://github.com/config-r/config-r/issues/199*

Should be added to the Wiki.

Should include the following important points:

* Web.csx should be set to 'do not copy', i.e. at runtime it should be sitting next Web.config
* Since assemblies live in the `bin/` folder, any references in web.csx should point to that folder, e.g. `#r bin/MyAssembly.dll`

**Comment by teabaggs** [comment]
@adamralph , I updated the [quickstart](https://github.com/config-r/config-r/wiki/Quickstart) with your notes from the original issue and an example.

**Comment by adamralph** [comment]
@teabaggs thanks very much!
