### ISSUE TITLE
Common.Logging still around

### ISSUE THREAD

**Issue by rmbrunet** [config-r/config-r#217]
Hello,

Just installed 0.13.0 and see that Common.Logging still around. Is that correct?

Update: I see that ScriptCs.Core and ScriptCs.Engine.Roslyn 0.15.0 have a dependency on Common.Logging.

Regards,

Roberto

**Comment by adamralph** [comment]
Yep, this is because there is still a transitive dependency on Common.Logging via the scriptcs packages. Common.Logging was only deprecated in scriptcs 0.15, but not removed.
