### ISSUE TITLE
CoreCLR support

### ISSUE THREAD

**Issue by filipw** [config-r/config-r#222]
I have been experimenting with moving this library to CoreCLR.

The functionality is fairly easy to port - but it's the tooling that will be a problem - liblog, xbehave, fluentAssertions and all of that doesn't work on CoreCLR.

I'll have some code to share soon, but let's use this thread for discussions.

**Comment by adamralph** [comment]
@filipw thanks for raising.

I presume we'd have to remove the dependency on scriptcs too? Unless scriptcs starts to support CoreCLR soon...

**Comment by filipw** [comment]
yeah I think there is much more value in having ConfigR on CoreCLR straight away even if it would mean a more feature limited version (both on the script side and on the tooling/dev side).

Then different pieces can be re-introduced as the world moves to CoreCLR.

**Comment by filipw** [comment]
this should be on hold until RC2 hits, it would wasted effort at this point

**Comment by adamralph** [comment]
Agreed.

**Comment by adamralph** [comment]
@filipw given the recent storm that's blown through the land of .NET 'next', do you think there is anything worth discussing in the near future? I don't see myself investing any time in .NET core support any time soon, so I'm leaning towards closing this. There's always https://gitter.im/config-r/config-r in the meantime.

When the time comes, I'm happy to work an issue to convert from .NET 4.6 to whichever [.NET Standard](https://gist.github.com/davidfowl/8939f305567e1755412d6dc0b8baf1b7) is the one implemented by .NET Core.

**Comment by filipw** [comment]
> given the recent storm

I bet you initially typed it differently 😄 
anyway, I agree, there is no point in investing effort until the tooling catches up - which - by the looks of it (especially in light of the `csproj`/`project.json`) won't be there for at least a good couple of months
